- alias: Living Room Lights On At Sunset
  initial_state: False
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.livingroom_lights
